### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/root/.ssh'

### ISSUE THREAD

**Issue by abriperez** [webfactory/ssh-agent#116]
Hello, I am having problems at the time the action tries to create de folder /root/.ssh/
I configured the action as follows:
```
- name: Container SSH Agent
        uses: PhutureCorp/container-ssh-agent@v0.0.1
        with:
          ssh-private-key: ${{secrets.KEY}}
          home-dir: "$USER ~/.ssh/known_hosts"
```
