### ISSUE TITLE
Not working on Windows: "Not treating it as a GitHub deploy key"

### ISSUE THREAD

**Issue by sfullerbeckman** [webfactory/ssh-agent#130]
See comment below for updated bug information: https://github.com/webfactory/ssh-agent/issues/130#issuecomment-1276577454

Old...
I am adding the below private key, which is stored in the repo's secrets. The corresponding public key is found as a deploy key in another repo within the same private Github organization. Below is the yaml where I am trying to install my private key.

```yaml
- name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ACCESS_KEY }}
```

When this is run, I get this. 

```
Key(s) added
Configuring deployment key(s)
...
Added deploy-key mapping: Use identity...
Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

What doest that last line mean? Does this mean that something went wrong? It looks like it thinks the public key is empty based on the empty quotes?
