### ISSUE TITLE
ssh-agent now working properly with msys2/setup-msys2

### ISSUE THREAD

**Issue by mojca** [webfactory/ssh-agent#149]
I cannot get the `ssh-agent` working in combination with https://github.com/msys2/setup-msys2

```
Cloning into 'private-repository-I-fetch-via-cmake-fetchcontent'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Example workflow:
```yaml
name: Test

on:
  push:

jobs:
  build-mingw-windows:
    runs-on: windows-2022
    name: Windows MinGW Clang

    strategy:
      matrix:
        include:
          - cmake_generator: Ninja
            cmake_defines: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
            mingw_msystem: mingw64
            mingw_env: x86_64

    # didn't work as advertised
    #defaults:
    #  run:
    #    shell: msys2 {0}

    steps:
      - name: Setup MinGW, install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_msystem }}
          # not sure which ones are really needed
          install: >-
            git
            ninja
          pacboy: >-
            cmake:p
            clang:p

      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # requires some private dependencies via CMake's FetchContents
      - name: Configure
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -G "${{ matrix.cmake_generator }}" --preset ${{ env.cmake_preset }} ${{ matrix.cmake_defines }} ..
```
