### ISSUE TITLE
Make this action work on Windows as well

### ISSUE THREAD

**Issue by Raynos** [webfactory/ssh-agent#15]
When using this github action on windows it's not happy as off two days ago.

I currently get the error

```
unable to start ssh-agent service, error :1058
```

I am currently trying to figure out what changed on windows 2019 on github actions ...

**Comment by Raynos** [comment]
I spend a full day trying to figure this out.

The following works for me.

```
    # The webfactory/ssh-agent module does not work on Windows anymore
    # I do not recommend touching this SSH stuff, i spend two days
    # tweaking it just to get it to work on windows -.-
    - name: Configure SSH
      run: Set-Service ssh-agent -StartupType Manual
    - name: Start SSH
      run: Start-Service ssh-agent
    - name: Add SSH key
      run: echo $env:SSH_PRIVATE_KEY | ssh-add -
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add github.com to known_hosts
      run: |
        mkdir ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
        npm ci
```

The important parts are to start the other SSH agent ... and to configure git to use the other SSH agent ...

Obvouisly `node` & `npm` are unrelated to `ssh-agent` but I only use `ssh-agent` for npm when it tries to `git clone` private github repositories.
