### ISSUE TITLE
SSH-Agent socket is not found by the docker/build-push-action step

### ISSUE THREAD

**Issue by andremandrade** [webfactory/ssh-agent#161]
I'm trying to use the  ssh-agent with docker/build-push-action.
I tested the same Dockerfile with ssh flag localy and it works this way:
```shell
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa 
docker build --ssh default=$SSH_AUTH_SOCK -t myacr.azurecr.io/myapp/api:latest .
```

My workflow.yaml

```yaml
      - name: Docker Metadata
        id: dockermeta
        uses: docker/metadata-action@v4
        with:
          images: myacr.azurecr.io/myapp/api
          tags: |
            type=sha
            type=ref,event=branch
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: 23...8e
          tenant-id: 48..a9
          subscription-id: f9..25
      
      - name: Login to ACR
        run: az acr login -n appnamespace
        shell: bash

      - name: SSH-Agent setup
        uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PK }}

      - name: Collect Git and SSH config files in a directory that is part of the Docker build context
        run: |
          mkdir root-config
          cp -r ~/.ssh root-config/
         // ~/.gitconfig was removed because it does not exist and cause failure
         
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./back
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}"
          tags: ${{ steps.dockermeta.outputs.tags }}
          labels: ${{ steps.dockermeta.outputs.labels }}
          push: true
```

I added this to the Dockerfile:
```dockerfile
COPY root-config /root/
RUN sed 's|/home/runner|/root|g' -i.bak /root/.ssh/config
```

The last step fails with the following error:

`ERROR: stat /tmp/ssh-XXXXXX9ilfNL/agent.2354": no such file or directory
Error: buildx failed with: ERROR: stat /tmp/ssh-XXXXXX9ilfNL/agent.2354": no such file or directory`
