### ISSUE TITLE
fata: repository 'github.com/olvrec/myrepo' does not exist

### ISSUE THREAD

**Issue by olvresc** [webfactory/ssh-agent#165]
Hello, encountering an error when using `webfactory/ssh-agent@v0.7.0`

````
git clone github.com/olvresc/aaa
  shell: /usr/bin/bash -e {0}
  env:
    SSH_AUTH_SOCK: /tmp/ssh-XXXXXXNIEYzk/agent.1584
    SSH_AGENT_PID: 1585
fatal: repository 'github.com/olvresc/aaa' does not exist
````

---

Worflow
````
name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH for private repository
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clone test
        run: |
           git clone github.com/olvresc/aaa
````

---

Error:

![image](https://user-images.githubusercontent.com/22219712/224591781-87bf2035-2e6f-4bb3-af60-3ac1412fe04b.png)

![image](https://user-images.githubusercontent.com/22219712/224591968-f8962158-3982-4b4a-9801-91cbf4c8618a.png)

---

Added my private key as `SSH_PRIVATE_KEY` and public key as deploy key with comment `git@github.com:olvresc/aaa.git`

**Comment by mpdude** [comment]
At first sight, configuration looks ok.

Could you try `git clone git@github.com:olvresc/aaa.git` as the URL please?

**Comment by olvresc** [comment]
> At first sight, configuration looks ok.
> 
> Could you try `git clone git@github.com:olvresc/aaa.git` as the URL please?

Hi, was able to clone the repository (on my machine)
```
$ git clone git@github.com:olvresc/aaa.git
Cloning into 'aaa'...
remote: Enumerating objects: 351, done.
remote: Counting objects: 100% (351/351), done.
remote: Compressing objects: 100% (254/254), done.
remote: Total 351 (delta 171), reused 268 (delta 88), pack-reused 0 eceiving objects:  59% (208/351)
Receiving objects: 100% (351/351), 91.40 KiB | 207.00 KiB/s, done.
Resolving deltas: 100% (171/171), done.
```

**Comment by OscarVanL** [comment]
This problem no longer happens for me with the latest ssh-agent. 

The only thing that has changed is that I'm now using `actions/checkout@v4` instead of v3:
```
      - uses: actions/checkout@v4
        with:
          submodules: true
```

My config now looks like:
```
      - uses: webfactory/ssh-agent@v0.8.0
         with:
           ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
           repo-mappings: github.com/foo/bar
      - uses: actions/checkout@v4
         with:
           submodules: true
```
