### ISSUE TITLE
Host key verification failed - Even demo file on v0.8.0 is broken

### ISSUE THREAD

**Issue by philippe-boyd-maxa** [webfactory/ssh-agent#177]
It seems that latest release following the update to the host keys broke everything...

Also, Demo github action no longer working : https://github.com/webfactory/ssh-agent/blob/master/.github/workflows/demo.yml

![image](https://user-images.githubusercontent.com/89592010/229006110-5c2136d1-58a0-4a16-b47d-64929591a9ea.png)
![image](https://user-images.githubusercontent.com/89592010/229006278-6b2e73a5-d0fc-4bcd-bf6b-f9854c6aae00.png)

**Comment by sebastiankugler** [comment]
@philippe-boyd-maxa where are you trying to run the action? If it's in a self-hosted environment, you have to provide the host keys yourself. If run in github.com, GitHub should provide the keys in the environment automatically: see https://github.com/webfactory/ssh-agent/pull/171#issuecomment-1482651132

**Comment by philippe-boyd-maxa** [comment]
@sebastiankugler I'm running it in github.com. And if you check the Actions page of THIS repository https://github.com/webfactory/ssh-agent/actions you'll see that even the demo action fails. That's what I'm mentioning in my original issue.

**Comment by mpdude** [comment]
Seems we have problems with Windows-based builds and actions running in Docker images…? For the latter, #174 might contain hints

**Comment by philippe-boyd-maxa** [comment]
The problem is not only with Windows but with the Docker demo also: see https://github.com/webfactory/ssh-agent/actions/runs/4511031704/jobs/7942696417#logs

**Comment by nullsurface** [comment]
I'm having this issue when running Poetry Install in GitHub Actions. "Host Key Verification" Fails after half of packages are installed with poetry. This issue started happening out of nowhere 2 weeks ago, so the timeline checkouts.

**Comment by 16L-YT** [comment]
I having the same error. My github action was based on ssh-agent v0.5.3 and after the breaking change in Github SSH, I used v0.8.0 and this is what I've done to setup the new generated private key: 

1- I've created new pair of SSH keys using this command
`ssh-keygen -t ed25519 -C "mail@website.net"` with no passphrase
2- updated the SSH_PRIVATE_KEY in secrets/actions with the generated private key.
3- Added the public key to 'Deploy keys'. 
4- I added this run command in the action to test the SSH connection with private repos
`- run: git ls-remote git@github.com:org/private-repo`

```
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                - run: git ls-remote git@github.com:org/private-repo
```

I always `get: fatal: Could not read from remote repository.`

5- I've tried to change the comment in the key generating command with `-c "git@github.com:org/private-repo" to help the action to match the provate key with the public key. It did not work.

**Comment by tan-wei-xin-alez** [comment]
Also having this issue when trying to run
```
    runs-on: ubuntu-latest
    container:
      image: <container_registry_url>/<image_name>:latest
    steps:
      # https://github.com/orgs/community/discussions/50130#discussioncomment-5322500
      - name: Checkout repo using ssh (so that submodules also use ssh)
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.ROBOT_SAFEPLCHANDLER_APP_DEPLOY_KEY_ED25519 }}

      # need to use ROBOT_SAFEPLCHANDLER_APP_DEPLOY_KEY_ED25519 twice as checkout action does not apply for LFS command
      - name: Supply ssh deploy keys for submodules and LFS
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.ROBOT_SAFEPLCHANDLER_APP_DEPLOY_KEY_ED25519 }}
            ${{ secrets.ROBOT_HELPERSCRIPTS_DEPLOY_KEY_ED25519 }}
            ${{ secrets.ROBOT_HELPERSCRIPTS_GETCALLERPREFERENCE_DEPLOY_KEY_ED25519 }}

      # https://github.com/actions/checkout/issues/287#issuecomment-1310504620
      - name: Pull LFS files and update submodules
        shell: bash
        run: |
          git lfs pull
          git submodule update --init --recursive
```

Reverting to v0.7.0 allows everything to work fine but otherwise, same "fatal: Could not read from remote repository" error that everyone above is experiencing

**Comment by RockLobster** [comment]
same issue here, 0.7.0 works, 0.8.0 fails

**Comment by ericksprengel** [comment]
same issue here, 0.7.0 works, 0.8.0 fails [2]

**Comment by speedym** [comment]
Same here, 0.8.0 fails on Windows runners.

**Comment by akram** [comment]
Hi this is what worked for me:

```
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Add GitHub to the SSH known hosts file"
      run: |
        mkdir -p -m 0700 /home/runner/.ssh
        curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' >> /home/runner/.ssh/known_hosts
        chmod 600 /home/runner/.ssh/known_hosts
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
```

and in `Dockerfile`

```
RUN --mount=type=ssh git clone git@github.com:my-repo/gh-action-test3.git

```

and create the key with:
```
ssh-keygen -b 4096 -t rsa -N "" -f my-key -C "git@github.com:my-repo/gh-action-test3.git"
```

And deploy the public key as a Deploy key in `github.com:my-repo/gh-action-test3.git`  and the  private key as an Action Secret in the repo running the GitHub Actions
