### ISSUE TITLE
SSH config cleanup not done

### ISSUE THREAD

**Issue by kcarlson** [webfactory/ssh-agent#184]
The modified git config is not cleaned up after a run, e.g. the `url git@key-` section.
This will affect a subsequent run on, for example, a self-hosted runner.

We are using a workaround which may help someone:

```yaml
- name: Restore git global config
  if: always()
  run: |
    MATCH=$(grep -o 'git@key-[^"]*\.github\.com:.*/[^"]*' ~/.gitconfig)
    git config --global --remove-section url.${MATCH}
````
