### ISSUE TITLE
Public Key Printed Out Even With log-public-key set to false

### ISSUE THREAD

**Issue by allan-mobley-jr** [webfactory/ssh-agent#193]
Using your GitHub action as follows:

```
name: Add SSH Key to Agent
uses: webfactory/ssh-agent@v0.8.0
with:
  ssh-private-key: ${{ secrets.MOBSITES_SSH_PRIVATE_KEY }}
  log-public-key: false
```

However, public key is still logged in GitHub Workflow logs when step runs.
