### ISSUE TITLE
Doesn't seem to put keys into /home/runner/.ssh

### ISSUE THREAD

**Issue by geoidesic** [webfactory/ssh-agent#198]
I had a go with this and it although I've put the private key into a secret and done:
```
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PVT_KEY }}
     
 ```
 
 It doesn't seem to find the key:
 ```
 debug1: Offering public key: --REDACTED-- agent
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Trying private key: /home/runner/.ssh/id_rsa
debug1: Trying private key: /home/runner/.ssh/id_ecdsa
debug1: Trying private key: /home/runner/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/runner/.ssh/id_ed25519
debug1: Trying private key: /home/runner/.ssh/id_ed25519_sk
debug1: Trying private key: /home/runner/.ssh/id_xmss
debug1: Trying private key: /home/runner/.ssh/id_dsa
debug1: No more authentication methods to try.
cicd@<redacted-ip-address> Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Error: Process completed with exit code 255.
 ```
 
If I add in a command to `ls ~/.ssh` the output shows only the `known_hosts` file, so it's not finding the private key as far as I can tell.
