### ISSUE TITLE
Error: does not match GitHub URL pattern. Not treating it as a GitHub deploy key on version 0.9.0

### ISSUE THREAD

**Issue by viral1701** [webfactory/ssh-agent#210]
Receiving error `does not match the GitHub URL pattern. I am not treating it as a GitHub deploy key on v0.9.0. Using an `action.yml`, there is not much going on the steps; however, it keeps failing to download the repo.

I am only downloading a single key. Below is my action.yml setup

```
    - name: Checkout Working Directory
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.SSH_PRIVATE_KEY }}

```

**Comment by eriweb** [comment]
Have the same, did you find a solution?

**Comment by dhuseby** [comment]
Did you generate your key with a comment that matches the other repo's url? https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys

**Comment by vaherdiana** [comment]
I think the problem is here: if you adjust the regex checking for the comment of public RSA key, adding escape there, it would recognise better.
![image](https://github.com/webfactory/ssh-agent/assets/146828798/0dfb8ce5-ec2e-4aa1-86c1-f72e20780cf5)

**Comment by sebastiankugler** [comment]
@vaherdiana Thanks a lot for the analysis! Would you be able to open a PR?

**Comment by vaherdiana** [comment]
No I would not dare yet, I am trying to figure out how it works myself. Created a copy of the repo, but getting permission issues, so cant really test and I don't want to propose anything without testing. WIP :)

**Comment by sebastiankugler** [comment]
@vaherdiana I just tested the [regex](https://github.com/webfactory/ssh-agent/blob/dc588b651fe13675774614f8e6a936a468676387/index.js#L57) myself in regex101.com. If you switch to "ECMAScript (Javascript)" you see that the `/` does not need to be escaped in JS.

<img width="1512" alt="Bildschirmfoto 2024-05-02 um 11 56 46" src="https://github.com/webfactory/ssh-agent/assets/4364200/61e68c4d-9db7-43b3-a9bd-e9432052f278">

So I don't think that this is the cause of the problem.

**Comment by ELHart05** [comment]
any solution?

**Comment by ELHart05** [comment]
After some research I used another package called appleboy/ssh-action and worked fine!

```yaml
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/youtube.com/
          git pull origin main
          git status
          npm install --only=prod
```
