### ISSUE TITLE
add ssh key for host?

### ISSUE THREAD

**Issue by nicola-lunghi** [webfactory/ssh-agent#215]
Hi
I need to execute some commands on a remote host via ssh like

```yaml
- run: scp -r myhost ./dev
- run: ssh myhost whoami
- run: ssh myhost /tmp/script1
```

can I use this extension to setup the ssh config file in the runner (and clean it up after the job has completed?
or this extension only supports github.com hosts?

(I was thinking of creating a key with `myuser@myhost.localdomain.com` as a comment)
