### ISSUE TITLE
The "file" argument must be of type string. Received undefined - in Post job

### ISSUE THREAD

**Issue by Constantin07** [webfactory/ssh-agent#219]
Hi,

Here is config used:

```yaml
      - name: Configure SSH key for Terraform components and modules
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TERRAFORM_MODULES_DEPLOY_KEY }}
```

In the post job, despite "green" I see the below message:

```shell
Post job cleanup.
Stopping SSH agent
The "file" argument must be of type string. Received undefined
Error stopping the SSH agent, proceeding anyway
```

<img width="520" alt="image" src="https://github.com/webfactory/ssh-agent/assets/11664677/0faaa141-f348-4e81-88fc-787ca754e76d">

Is this expected behaviour or can be fixed ?
