### ISSUE TITLE
Example Usage is Unclear

### ISSUE THREAD

**Issue by ray-winkelman** [webfactory/ssh-agent#22]
It's unclear how to issue a command on the host once an ssh connection is established. Please provide an example. In the example below, I'd like to run the php command on the host, rather than the action environment. 

```
    - name: SSH Into Env
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Remotely Create Symbolic Link for Storage
      run: php artisan storage:link
```

![image](https://user-images.githubusercontent.com/8670829/76151279-ac8e1480-6089-11ea-88b2-081add1b5aee.png)
