### ISSUE TITLE
Error: Input does not meet YAML 1.2 "Core Schema" specification: log-public-key

### ISSUE THREAD

**Issue by fancyTyphoonKitty** [webfactory/ssh-agent#225]
Hello,

I'm trying to leverage this action with a self-hosted runner using a container (not the runner agent). I'm not really doing anything too fancy, but when the step runs, it fails with the error **Error: Input does not meet YAML 1.2 "Core Schema" specification: log-public-key**.

```yaml
#truncated
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:

          ssh-private-key: |
            ${{ secrets.SSH_DEPLOY_KEY }}

#truncated
```
When reviewing the action.yml file is vscode, I did notice that the Github Actions vscode extension was flagging the default value for the input in question. Stating **Incorrect type. Expected "string".yaml-schema: GitHub Action**.

![image](https://github.com/user-attachments/assets/6bd05b0a-bfbd-48aa-a534-381177ae32a8)
