### ISSUE TITLE
When using multiple keys, only the first one is detected

### ISSUE THREAD

**Issue by Pierre-FrancoisHau** [webfactory/ssh-agent#228]
Hello, here is what my YAML file looks like:

`
myTitle:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.SSH_KEY_ONE }}
          ${{ secrets.SSH_Key_TWO }}
          
 `

          
          
I've tried it with just the first key and just the second key, and they both work. However, when I use two keys at the same time, only one seems to be detected. Is there something I’m missing?

**Comment by malyavi-nochum** [comment]
We're having the same issue. Seems like the comments are not saved in deploy keys (anymore?) and so ssh-agent isn't recognizing them

**Comment by rupurt** [comment]
As a temporary workaround if you have 1 new key you can put the new key at the top and it will be used as the default

**Comment by paigeadelethompson** [comment]
theres no work around, you just shouldn't use ssh agent this way because they didn't think this through. What I'm gonna have to do is basically add each dependency as a subtree in each repository which really sucks I'm mad about it but whatever do it, don't look back and be done with it.

**Comment by mprimi** [comment]
Just bumped into this. Same result: whichever key is first is used, the rest seem to be ignored.

Maybe this setup should not be advertised in the frontpage/readme, given that it is known **not** to work.
More people will bang their head against this.

https://github.com/webfactory/ssh-agent/pull/238/

**Comment by mprimi** [comment]
Suggested workaround for whoever is reading this: set and use one key at the time.

For example i want to refresh 2 submodules that have 2 different deploy keys. The following seems to work:

```
      - name: Add SSH key for private submodule A
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_A_KEY }}

      - name: "Update submodule A"
        run: |
            git submodule update --init --remote --checkout --recommend-shallow path/to/A.git

      - name: Add SSH key for private submodule B
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_B_KEY }}

      - name: "Update submodule B"
        run: |
            git submodule update --init --remote --checkout --recommend-shallow path/to/B.git
```
