### ISSUE TITLE
Windows: unable to clone, with error message `ssh: Could not resolve hostname key-<SHA>.github.com: Name or service not known`

### ISSUE THREAD

**Issue by DilumAluthge** [webfactory/ssh-agent#230]
I see a few open issues that look similar to this, but not exactly the same, so I figured I'd open a new issue. Feel free to close if this is a duplicate.

For example, this might be a duplicate of #148.

## Version info

I am able to reproduce this bug using version v0.9.0 (dc588b651fe13675774614f8e6a936a468676387) of this action.

## Description of the bug

On Windows, I am unable to clone, with the error message looking something like this:

```
ssh: Could not resolve hostname key-<SHA>.github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Workaround

I'm able to get things to work by setting the `GIT_SSH_COMMAND` environment variable as follows:

```yaml
- name: Set GIT_SSH_COMMAND on Windows
  if: runner.os == 'Windows'
  shell: bash
  run: |
    echo "GIT_SSH_COMMAND=ssh -F /c/Users/MY_USERNAME/.ssh/config -o \"UserKnownHostsFile /c/Users/MY_USERNAME/.ssh/known_hosts\"" >> "${GITHUB_ENV:?}"
```

Replace `/c/Users/MY_USERNAME/` with the correct home directory. On GitHub-hosted Windows runners, this will probably be `/c/Users/runneradmin`. For self-hosted Windows runners, this will depend on your CI setup.
