### ISSUE TITLE
Error loading key "(stdin)": error in libcrypto

### ISSUE THREAD

**Issue by nazikus** [webfactory/ssh-agent#233]
I get this error no matter what.

Double checked my key and added newline at the end of secret `SSH_KEY`:
```
-----BEGIN OPENSSH PRIVATE KEY----- <content> -----END OPENSSH PRIVATE KEY-----\n
```
Tried versions 0.9.0, 0.8.0, 0.7.0 - the same result.

```yml
- name: Setup SSH agent for git
  uses: webfactory/ssh-agent@v0.9.0
  with:
    ssh-private-key: ${{ secrets.SSH_KEY }}

```

![image](https://github.com/user-attachments/assets/8b3c95bb-43dc-4fe1-aae7-d855ac38c5da)

Any help appreciated.
Thank you
