### ISSUE TITLE
Clone Private Repo failed

### ISSUE THREAD

**Issue by zhulinpinyu** [webfactory/ssh-agent#25]
actions config

```yml
runs-on: ubuntu-latest
container:
      image: elixir:1.9.1-slim
      env:
        MIX_ENV: test
steps:
  - name: Checkout
    uses: actions/checkout@v1
  - name: create SSH key
    uses: webfactory/ssh-agent@v0.2.0
    with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  - name: Install Dependencies
    run: |
        git clone git@github.com:zhulinpinyu/sf.git
```

**error log:**
```bash
Run git clone git@github.com:zhulinpinyu/sf.git
  git clone git@github.com:zhulinpinyu/sf.git
  shell: sh -e {0}
  env:
    SSH_AUTH_SOCK: /tmp/ssh-auth.sock
Cloning into 'sf'...
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
##[error]Process completed with exit code 128.
```
