### ISSUE TITLE
Still got error fatal: repository not found

### ISSUE THREAD

**Issue by abinhho** [webfactory/ssh-agent#28]
Hello,
I am still facing with fatal error after use `webfactory/ssh-agent`
```
fatal: repository 'https://github.com/mycompany/mycompany-package.git/' not found
```

This is my deploy flow
```
name: CI Dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set SSH Key Agent
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v2
        
    - name: Install node modules
      run: yarn

```

This is error
![Screen Shot 0002-05-16 at 18 42 05](https://user-images.githubusercontent.com/9253378/82118994-fd666b80-97a4-11ea-97e3-6aaad991ee4f.png)

This is `package.json`
```
{
    ...
    "mycompany-package": "git+https://github.com/mycompany/mycompany-package.git",
    ....
}
```

Please help!
