### ISSUE TITLE
Post-run actions on multi-usage

### ISSUE THREAD

**Issue by chkpnt** [webfactory/ssh-agent#32]
First of all, thanks for this GH-Action :-)

I'm using this action twice in my workflow because using a ssh-agent with multiple keys doesn't seem to work with the Gradle-plugin I'm using to push some data to Git-Repositories over ssh. 

```yaml
[...]
      - uses: webfactory/ssh-agent@v0.3.0
        with:
          ssh-private-key: ${{ secrets.WORKFLOW_SSH_KEY }}
        continue-on-error: true
      - name: Push data, if there are any changes
        run: ./gradlew gitPublishPush --info

      - uses: webfactory/ssh-agent@v0.3.0
        with:
          ssh-private-key: ${{ secrets.WORKFLOW_SSH_KEY_ARCHIV_REPO }}
        continue-on-error: true
      - name: Archive the PDFs in a private repo
        run: ./gradlew -b archive.gradle.kts gitPublishPush --info
```

This works fine, but I have to use `continue-on-error` because otherwise, the second post-run-action (which belongs to the first ssh-agent) fails:

<img width="611" alt="grafik" src="https://user-images.githubusercontent.com/1956979/85326234-40ff7400-b4cd-11ea-8697-84ca9235c136.png">

Can I somehow trigger the post-run action manually at an earlier step?

Otherwise, I suggest to check in `cleanup.js`, if the process is already killed.
https://github.com/webfactory/ssh-agent/blob/8789658b02527d79b3939a5bfc202ea55f91ab32/cleanup.js#L7
