### ISSUE TITLE
Github actions deprecating set-env and add-path commands

### ISSUE THREAD

**Issue by ButuzGOL** [webfactory/ssh-agent#45]
Error loading key "(stdin)": invalid format
Error: Command failed: ssh-add -

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by mpdude** [comment]
https://github.com/webfactory/ssh-agent/releases/tag/v0.4.1

**Comment by ButuzGOL** [comment]
Here my config
```
steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SWAMY_PRIVATE }}
```

but still getting error

Run webfactory/ssh-agent@v0.4.1
  with:
    ssh-private-key: ***
Adding GitHub.com keys to /home/runner/.ssh/known_hosts
Starting ssh-agent
Adding private key to agent
Error loading key "(stdin)": invalid format
Error: Command failed: ssh-add -
Error loading key "(stdin)": invalid format
