### ISSUE TITLE
Command failed: ssh-add -

### ISSUE THREAD

**Issue by pablosproject** [webfactory/ssh-agent#54]
Hi, I have been having issue today with this error `Command failed: ssh-add -`. I have been using this action for long time and never had a problem, could you help me debug what's wrong?

Here my workflow file:
```yaml
name: Test Registry packace

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish on the server
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SSH key for remote host
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Create a docker context for remote machine
        run: docker context create digital_ocean --docker="host=${{secrets.DO_HOST}}"

      - name: Launch new configuration
        run: docker-compose --context digital_ocean -f docker-compose.prod.yml up -d --build --force-recreate

      - name: Logout from docker
        run: docker logout

```

And here the error I got.

<img width="1331" alt="Screenshot 2020-11-27 at 21 02 27" src="https://user-images.githubusercontent.com/1416964/100481281-e1e50180-30f3-11eb-8cea-87427d18417c.png">
