### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by henry2004y** [webfactory/ssh-agent#60]
By scanning through the README file and existing issues, I understand that this is probably not an issue with `ssh-agent`. However, I still couldn't make it work after several attempts.

I want to take advantage of this action to copy test data from my local server.
By following the procedures, first I have
```
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.CI_PRIVATE_KEY }}
    - name: Reference data
      run: |
        scp -o 'ProxyCommand ssh username@login.server1 -W %h:%p' username@server2:filename .
        cat filename
```
The private keys should have been properly set, and public keys are added both to the proxy and actual servers.

The runlog first displays
```
Run webfactory/ssh-agent@v0.5.0
Adding GitHub.com keys to /home/runner/.ssh/known_hosts
Starting ssh-agent
Adding private key to agent
Identity added: (stdin) (username@legion5)
Keys added:
256 SHA256:JP1loMqqwOspXFAwP44oeAbuaUV/OlATxEPxrEwOcDs username@legion5 (ED25519)
```

and then
```
Run scp -o 'ProxyCommand ssh username@server1 -W %h:%p' username@server2:filename .
Host key verification failed.
ssh_exchange_identification: Connection closed by remote host
Error: Process completed with exit code 1.
```

After some search, the general suggestion I found for dealing with the `Host key verification failed` msg was by using `ssh-keygen`, but I had no luck in a successful attempt. Can you kindly offer me some help?

Thanks!
