### ISSUE TITLE
ssh-agent not starting on container based workflow

### ISSUE THREAD

**Issue by shashank11p** [webfactory/ssh-agent#65]
I am running a workflow on ubuntu-20.04 with container centos:7. 

```
job-name:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY }}
            ${{ secrets.SSH_KEY_2 }}
```
I get this error while starting the ssh-agent. 
```
Adding GitHub.com keys to /root/.ssh/known_hosts
Starting ssh-agent
Error: spawnSync ssh-agent ENOENT
```

Can someone help me fix this?
