### ISSUE TITLE
Deploy key not "treated as deploy key"

### ISSUE THREAD

**Issue by rr-james-hickman** [webfactory/ssh-agent#73]
I have followed the guide to setup a deploy key on a private git repo for a Swift Package.

I generated new SSH in the private SP repo using this command: `ssh-keygen -b 4096 -t rsa -N "" -f key -C "git@github.com:my-org/my-swift-package-repo.git"`
I have added the .ssh/key files (private/public) and the config file with GitHub.com host to the private SP repo.
I have added the public key as a deploy key on the private SP repo.
I have added the private key as a secret on the other repo that has an app using the SP as a dependency.

No matter what, I get this error:
```
Comment for key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.

xcodebuild: error: Could not resolve package dependencies:
10
  The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.
```

Here is my yaml:
```
      - name: Set SSH Key for remote host
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SPM_SSH_PUBLIC_KEY }}
```

Any help would be greatly appreciated!
