### ISSUE TITLE
Multiple Deploy Keys in docker build fails

### ISSUE THREAD

**Issue by iamnoah** [webfactory/ssh-agent#78]
Not exactly a bug, but I found it challenging to find a solution that works with docker build when using multiple deploy keys. The reason seems to be that the build container doesn't have the ssh and git config necessary to map the right key to the right repo.

For example:

```yaml
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_A }}
            ${{ secrets.DEPLOY_KEY_B }}
      - name: Works Well!
        run: |
          git clone github.com/me/private-repo-a
          git clone github.com/me/private-repo-b
      - name: Doesn't work :(
        run: |
          cat > Dockerfile <<EOF
          FROM debian
          RUN --mount=type=ssh git clone github.com/me/private-repo-a
          RUN --mount=type=ssh git clone github.com/me/private-repo-b
          EOF
          docker build --ssh default .
```

The docker build has access to the keys, but it doesn't use the right one for each repo, so one of the checkouts will fail.

My solution was to copy the config into the container:

```yaml
run: |
  mkdir root-config
  cp -r ~/.gitconfig  ~/.ssh root-config/
  docker build ... .
```

And in my Dockerfile:
```Dockerfile
COPY root-config /root/
RUN sed 's|/home/runner|/root|g' -i.bak /root/.ssh/config
```

That works, but it feels pretty hacky.  I was just wondering if anyone can come up with a better way/wanted to document a way to make it work.

**Comment by mpdude** [comment]
I don’t see how this is related to the action…?
 
 Could you explain please?

**Comment by iamnoah** [comment]
@mpdude sorry, I've edited to add some context. The action is incredibly useful.

**Comment by mpdude** [comment]
Ok, I think I now understand what this is about.

Not sure I can really help, but we can keep this open for some time to get some visibility.

Thoughts:

- Is it possible to mount the relevant directories/config files at `docker build` time instead of having to copy them?

- You could try if the SSH config file supports `~` for paths. Maybe that could make the `sed` command unnecessary (if we can adapt in this action).

Does that help?

**Comment by mpdude** [comment]
I guess the problem is not having the SSH with sock itself available, but the necessary mapping in .gitconfig and .ssh/config to map the right keys to the right repos.

**Comment by iamnoah** [comment]
I think `~` in the SSH config should work, but I have not found anything else that simplifies the setup unfortunately. There is a [2 year old buildkit issue](https://github.com/moby/buildkit/issues/970) for mounting directories as secrets during a build, which could make it safer to do (the COPY I do in my build is only safe because it is multi-stage and the home directory doesn't get copied over.)

**Comment by mpdude** [comment]
Buildkit support for such things would of course be best.

I also would not want to have ~/.ssh in intermediate layers of my images, but at least there is no sensitive data in this file. 

I am not sure about .gitconfig, though – it might be that `actions/checkout` leaves a secret token in that?

**Comment by aingham** [comment]
@mpdude I'm interested in following this, as it's exactly the same issue that I came across - you've summarised it really well.

Copying the git and ssh configs and keys into the container, as you suggested, did work for me, but the problem with that is that the private keys are then sitting in the Docker container. It would be better if it could make use of the keys that have been made available to it via ssh agent forwarding - I guess you haven't found a way of doing that?

**Comment by maxyousif15** [comment]
Not related to docker, but I am also encountering issues with multiple deploy keys.

I have followed the usual set up of:
- creating SSH keys (PEM with the comments outlined as specified by README, e.g. `ssh-keygen -t rsa -b 4096 -C "git@github.com:some_owner/some_repo.git" -m PEM`
- adding public component as deploy key for private dependency
- adding private as secret to repo of interest (repo pulling this private dependency)

Using `v0.5.3`, this is what I see in the workflow output - seems related to not being able to parse the comment correct and recognise deploy keys:

```
2021-07-26T10:57:05.7794800Z env:
2021-07-26T10:57:05.7796581Z   GITHUB_TOKEN: ***
2021-07-26T10:57:05.7798527Z   pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
2021-07-26T10:57:05.7806040Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib
2021-07-26T10:57:05.7807692Z ##[endgroup]
2021-07-26T10:57:05.8422742Z Adding GitHub.com keys to /home/runner/.ssh/known_hosts
2021-07-26T10:57:05.8436751Z Starting ssh-agent
2021-07-26T10:57:05.8765906Z SSH_AUTH_SOCK=/tmp/ssh-az1ZZWNazbO4/agent.1585
2021-07-26T10:57:05.8768382Z SSH_AGENT_PID=1586
2021-07-26T10:57:05.8770059Z Adding private key(s) to agent
2021-07-26T10:57:05.8991691Z Identity added: (stdin) ((stdin))
2021-07-26T10:57:05.9097294Z Identity added: (stdin) ((stdin))
2021-07-26T10:57:05.9099336Z Key(s) added:
2021-07-26T10:57:05.9138860Z 4096 SHA256:****.. (stdin) (RSA)
2021-07-26T10:57:05.9142390Z 4096 SHA256:****.. (stdin) (RSA)
2021-07-26T10:57:05.9150853Z Configuring deployment key(s)
2021-07-26T10:57:05.9215038Z Comment for key 'ssh-rsa blah blah (stdin)' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
2021-07-26T10:57:05.9265081Z Comment for key 'ssh-rsa blah blah (stdin)' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
2021-07-26T10:57:05.9287781Z Comment for key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

Not sure why it is implying that it is looking for comments in a 3rd key also, when only two keys are required.

**Comment by mpdude** [comment]
@aingham See the initial comment how the SSH Agent socket can be mounted for a `RUN` command at build time. You don’t have to (and almost never should) copy private SSH keys into a Docker image unless you absolutely understand the implications. 

@iamnoah any idea how we could proceed here?

**Comment by iamnoah** [comment]
So [this answer](https://superuser.com/questions/273037/using-the-identityfile-directive-in-ssh-config-when-agentforwarding-is-in-use) suggests that we could copy just the public keys into the docker container, and use them as the IdentityFile in .ssh/config to pick the correct key from the agent. So no private keys would end up in the container. I'll test this out when I can.

.gitconfig should not have anything sensitive in it.

**Comment by iamnoah** [comment]
I didn't realize the `key-*` files in `~/.ssh` already were just the public keys. So I think that while copying the contents of ~/.ssh into a container is less than ideal, it is at least not disclosing anything meant to be secret and is the best we can do with Docker at the moment.

Thanks for a very helpful action.

**Comment by hardbyte** [comment]
Very interested if someone has a non-hacky solution to this. It seems the logic that ssh-agent goes through to configure the git aliases needs to occur inside a docker container

**Comment by mrajancsr** [comment]
this is constantly breaking for me.  What am i doing wrong here? 
# syntax = docker/dockerfile:1.0-experimental
FROM python:3.9

# create a folder and cd into it
run mkdir temp_repo
run cd temp_repo

# set folder as current working directory
workdir /temp_repo

# move hello_world.py script from our local system to current workdir in docker
add hello_world.py .

# copy the requirements file from current system to docker directory
copy requirements.txt /temp_repo
run pip install -r requirements.txt


copy .gitconfig* /etc/gitconfig
copy ssh/config* /etc/ssh/ssh_config
copy ssh /home/runner/.ssh
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh pip install git+ssh://git@github.com/my_company/repo1.git
RUN --mount=type=ssh git clone git+ssh://git@github.com/my_company/repo1.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/my_company/repo2.git

copy timescale.pem /root

run apt-get update -y


cmd ["python", "-u", "hello_world.py"]


Its constantly failing on the last step with repository not found error.  can someone please help?

**Comment by nicolo-kira** [comment]
While this is a bit of an older issue, I seemed to have solved this with our build process by doing something like this

Posting here for any other who come across this

```
    # Setup SSH_AUTH_SOCK to pull from other git repos during the build
    - name: Setup SSH_AUTH_SOCK Repo A
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_A_DEPLOY_KEY }}
        ssh-auth-sock: /tmp/repo-a-${{ github.sha }}.sock

    - name: Setup SSH_AUTH_SOCK Repo B
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_B_DEPLOY_KEY }}
        ssh-auth-sock: /tmp/repo-b-${{ github.sha }}.sock

    # Sets up buildx to enable docker buildkit features
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true # docker build alias for buildx

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myregistry/myrepo:latest
        file: Dockerfile
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
          repoa=/tmp/repo-a-${{ github.sha }}.sock
          repob=/tmp/repo-b-${{ github.sha }}.sock
```

This sets up separate ssh mount IDs you can reference in your build file:

```
# Repo A action
RUN --mount=type=ssh,id=repoa git clone git@github.com:org/repo-a.git .

# Repo B Action
RUN --mount=type=ssh,id=repob yarn install --frozen-lockfile
```
