### ISSUE TITLE
Comment for key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.

### ISSUE THREAD

**Issue by dingo-d** [webfactory/ssh-agent#87]
Hi!

Not sure what I'm doing wrong, this usually works when I have dedicated DevOps who handle the ssh for me, but this time I have to set the deployment of an app myself and I'm not sure what am I missing. 

So on the server, I generated new keys for deployment only using

```bash
ssh-keygen -t ed25519 -C "git@github.com:dingo-d/private-repo.git"
```

This created a public and private ed25519 key pair (id_ed25519.pub/id_ed25519). I've stored the public key as my deploy key in the repository, with read access.

In my secrets I've added the private key as a repo secret I'm using in the deploy step. Part of my actions for GH deployment looks like this

```yaml
steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2, deployer, wp-cli

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Add staging SSH key
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.STAGING_KEY }}

      - name: Deploy application to staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          admin_user: ${{ secrets.ADMIN_USER }}
          admin_email: ${{ secrets.ADMIN_EMAIL }}
          admin_password: ${{ secrets.ADMIN_PASSWORD }}
          staging_secrets: ${{ secrets.STAGING_SECRETS }}
        run: |
          deployer deploy "$admin_user" "$admin_email" "$admin_password" "$staging_secrets" staging
```

When the action runs I see the following:

```bash
Run webfactory/ssh-agent@v0.5.3
  with:
    ssh-private-key: ***
Adding GitHub.com keys to /home/runner/.ssh/known_hosts
Starting ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-5uiRWTP2VlxE/agent.1905
SSH_AGENT_PID=1906
Adding private key(s) to agent
Identity added: (stdin) (git@github.com:dingo-d/private-repo.git)
Key(s) added:
256 SHA256:..... git@github.com:dingo-d/private-repo.git (ED25519)
Configuring deployment key(s)
Added deploy-key mapping: Use identity '/home/runner/.ssh/key-....' for GitHub repository dingo-d/private-repo
Comment for key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

Then my deploy task fails with

```bash
 The command "rm -f ~/www//www/.../public/.dep/deploy.lock  
  " failed.                                                                    
                                                                               
  Exit Code: -1 (Unknown error)                                                
                                                                               
  Host Name: 35.245.151.137                                                    
                                                                               
  ================                                                             
  Warning: Permanently added '[ip address]:port' (ECDSA) to the list of   
  known hosts.                                                                 
  Permission denied, please try again.                                         
  Permission denied, please try again.                                         
  user@ip: Permission denied (publickey,password).    
```

I'm not sure which part of the steps am I missing.

### EDIT

I've added a clone task to see if it works, and it passes

```bash
Run git clone git@github.com:dingo-d/private-repo.git
  git clone git@github.com:dingo-d/private-repo.git
  shell: /usr/bin/bash -e ***0***
  env:
    SSH_AUTH_SOCK: /tmp/ssh-tEuJgI0eg1UD/agent.1880
    SSH_AGENT_PID: 1881
Cloning into 'private-repo'...
Warning: Permanently added the RSA host key for IP address 'ip address' to the list of known hosts.
```

### EDIT 2

Could it be because the server expects the password? I noticed that when I added my ssh key to the list of `authorized_keys` on the server I couldn't ssh to it, but when I'd remove it I could enter but with a password/
