### ISSUE TITLE
Very silly question: how is it supposed to be used?

### ISSUE THREAD

**Issue by KubaO** [webfactory/ssh-agent#91]
The top-level readme has no mention of how to actually use this thing. Yes, I know how to add the keys, but how do we actually consume the keys?

This doesn't work - and that's what most people would expect should be working, otherwise what's the point?

```
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
                ${{ secrets.repo1}}
                ${{ secrets.repo2}}
      - uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive
```

The example in the readme also has the checkout preceding the ssh-agent setup, and that won't ever work since the keys need to be set up when the checkout happens, not before. So I'm a bit baffled as to what this is supposed to be doing...
